USE srmc;

-- 删除无用的旧表
DROP TABLE IF EXISTS processes;
DROP TABLE IF EXISTS programs;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS servers;

-- 删除app_services中无用的字段
ALTER TABLE app_services
  DROP COLUMN IF EXISTS cluster_name,
  DROP COLUMN IF EXISTS node_count,
  DROP COLUMN IF EXISTS master_node,
  DROP COLUMN IF EXISTS data_nodes,
  DROP COLUMN IF EXISTS redis_role,
  DROP COLUMN IF EXISTS redis_memory_usage,
  DROP COLUMN IF EXISTS redis_key_count,
  DROP COLUMN IF EXISTS mysql_version,
  DROP COLUMN IF EXISTS mysql_connection_count,
  DROP COLUMN IF EXISTS mysql_slave_status,
  DROP COLUMN IF EXISTS mysql_db_count,
  DROP COLUMN IF EXISTS status,
  DROP COLUMN IF EXISTS cpu_usage,
  DROP COLUMN IF EXISTS memory_usage,
  DROP COLUMN IF EXISTS disk_usage,
  DROP COLUMN IF EXISTS network_io;

-- 修改表注释
ALTER TABLE app_services MODIFY COLUMN id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE app_services MODIFY COLUMN project_id INT NOT NULL COMMENT '所属项目ID';
ALTER TABLE app_services MODIFY COLUMN subsystem_id INT COMMENT '子系统ID';
ALTER TABLE app_services MODIFY COLUMN group_id INT COMMENT '程序分类ID';
ALTER TABLE app_services MODIFY COLUMN func_desc VARCHAR(255) NOT NULL COMMENT '功能描述';
ALTER TABLE app_services MODIFY COLUMN module VARCHAR(100) COMMENT '对应模块';
ALTER TABLE app_services MODIFY COLUMN ip VARCHAR(45) NOT NULL COMMENT '服务器IP';
ALTER TABLE app_services MODIFY COLUMN ssh_port INT DEFAULT 22 COMMENT 'SSH端口';
ALTER TABLE app_services MODIFY COLUMN username VARCHAR(100) NOT NULL COMMENT 'SSH用户名';
ALTER TABLE app_services MODIFY COLUMN password VARCHAR(500) NOT NULL COMMENT 'AES-256-GCM加密密码';
ALTER TABLE app_services MODIFY COLUMN program_path VARCHAR(500) COMMENT '程序路径';
ALTER TABLE app_services MODIFY COLUMN start_script VARCHAR(500) COMMENT '启动脚本';
ALTER TABLE app_services MODIFY COLUMN stop_script VARCHAR(500) COMMENT '停止脚本';
ALTER TABLE app_services MODIFY COLUMN log_path VARCHAR(500) COMMENT '日志路径';
ALTER TABLE app_services MODIFY COLUMN port VARCHAR(255) COMMENT '程序端口（逗号分隔）';
ALTER TABLE app_services MODIFY COLUMN owner VARCHAR(100) COMMENT '负责人';
ALTER TABLE app_services MODIFY COLUMN remark TEXT COMMENT '备注';
ALTER TABLE app_services MODIFY COLUMN service_type ENUM('HOST_APP','DOCKER') DEFAULT 'HOST_APP' COMMENT '服务类型';
ALTER TABLE app_services MODIFY COLUMN deploy_type ENUM('HOST','DOCKER') DEFAULT 'HOST' COMMENT '部署方式';
ALTER TABLE app_services MODIFY COLUMN instance_name VARCHAR(255) COMMENT '运行实例名称';
ALTER TABLE app_services MODIFY COLUMN container_name VARCHAR(255) COMMENT '容器名称';
ALTER TABLE app_services MODIFY COLUMN image_name VARCHAR(255) COMMENT '镜像名称';
ALTER TABLE app_services MODIFY COLUMN image_tag VARCHAR(100) COMMENT '镜像版本';
ALTER TABLE app_services MODIFY COLUMN container_id VARCHAR(64) COMMENT '容器ID';
ALTER TABLE app_services MODIFY COLUMN port_mapping VARCHAR(500) COMMENT '端口映射';
ALTER TABLE app_services MODIFY COLUMN volume_mapping VARCHAR(1000) COMMENT 'Volume挂载';
ALTER TABLE app_services MODIFY COLUMN network_mode VARCHAR(100) COMMENT '网络模式';
ALTER TABLE app_services MODIFY COLUMN log_type VARCHAR(50) COMMENT '日志类型';

ALTER TABLE audit_logs MODIFY COLUMN id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE audit_logs MODIFY COLUMN user_id BIGINT COMMENT '用户ID';
ALTER TABLE audit_logs MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '用户名';
ALTER TABLE audit_logs MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '操作类型';
ALTER TABLE audit_logs MODIFY COLUMN service_id BIGINT COMMENT '服务ID';
ALTER TABLE audit_logs MODIFY COLUMN service_code VARCHAR(64) COMMENT '服务编码';
ALTER TABLE audit_logs MODIFY COLUMN server_id BIGINT COMMENT '服务器ID';
ALTER TABLE audit_logs MODIFY COLUMN ip VARCHAR(45) COMMENT 'IP地址';
ALTER TABLE audit_logs MODIFY COLUMN result VARCHAR(20) NOT NULL COMMENT '执行结果';
ALTER TABLE audit_logs MODIFY COLUMN output TEXT COMMENT '输出内容';
ALTER TABLE audit_logs MODIFY COLUMN duration BIGINT COMMENT '执行时长(毫秒)';

ALTER TABLE projects MODIFY COLUMN id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE projects MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '项目名称';
ALTER TABLE projects MODIFY COLUMN code VARCHAR(50) COMMENT '项目编码';
ALTER TABLE projects MODIFY COLUMN description TEXT COMMENT '项目描述';

ALTER TABLE subsystems MODIFY COLUMN id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE subsystems MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID';
ALTER TABLE subsystems MODIFY COLUMN subsystem_name VARCHAR(100) NOT NULL COMMENT '子系统名称';
ALTER TABLE subsystems MODIFY COLUMN subsystem_code VARCHAR(50) NOT NULL COMMENT '子系统编码';
ALTER TABLE subsystems MODIFY COLUMN display_order INT DEFAULT 0 COMMENT '显示顺序';
ALTER TABLE subsystems MODIFY COLUMN description TEXT COMMENT '描述';

ALTER TABLE service_groups MODIFY COLUMN id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE service_groups MODIFY COLUMN group_name VARCHAR(100) NOT NULL COMMENT '分类名称';
ALTER TABLE service_groups MODIFY COLUMN group_code VARCHAR(50) NOT NULL COMMENT '分类编码';
ALTER TABLE service_groups MODIFY COLUMN display_order INT DEFAULT 0 COMMENT '显示顺序';
ALTER TABLE service_groups MODIFY COLUMN description TEXT COMMENT '描述';

ALTER TABLE subsystem_group_relations MODIFY COLUMN id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE subsystem_group_relations MODIFY COLUMN subsystem_id INT NOT NULL COMMENT '子系统ID';
ALTER TABLE subsystem_group_relations MODIFY COLUMN group_code INT NOT NULL COMMENT '程序分类ID';

ALTER TABLE sql_exec_history MODIFY COLUMN id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE sql_exec_history MODIFY COLUMN user_id BIGINT COMMENT '用户ID';
ALTER TABLE sql_exec_history MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '用户名';
ALTER TABLE sql_exec_history MODIFY COLUMN service_id BIGINT COMMENT '服务ID';
ALTER TABLE sql_exec_history MODIFY COLUMN service_code VARCHAR(64) COMMENT '服务编码';
ALTER TABLE sql_exec_history MODIFY COLUMN sql_statement TEXT NOT NULL COMMENT 'SQL语句';
ALTER TABLE sql_exec_history MODIFY COLUMN execution_time BIGINT COMMENT '执行时间(毫秒)';
ALTER TABLE sql_exec_history MODIFY COLUMN result_count BIGINT COMMENT '结果数量';
ALTER TABLE sql_exec_history MODIFY COLUMN error_message TEXT COMMENT '错误信息';

ALTER TABLE users MODIFY COLUMN id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID';
ALTER TABLE users MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '用户名';
ALTER TABLE users MODIFY COLUMN password VARCHAR(256) NOT NULL COMMENT '密码(BCrypt)';
ALTER TABLE users MODIFY COLUMN role VARCHAR(20) NOT NULL COMMENT '角色';
ALTER TABLE users MODIFY COLUMN email VARCHAR(128) COMMENT '邮箱';
ALTER TABLE users MODIFY COLUMN phone VARCHAR(20) COMMENT '手机号';
ALTER TABLE users MODIFY COLUMN is_active TINYINT(1) DEFAULT 1 COMMENT '是否激活';

OPTIMIZE TABLE app_services;
OPTIMIZE TABLE audit_logs;
OPTIMIZE TABLE projects;
OPTIMIZE TABLE subsystems;
OPTIMIZE TABLE service_groups;
OPTIMIZE TABLE subsystem_group_relations;
OPTIMIZE TABLE sql_exec_history;
OPTIMIZE TABLE users;

SELECT '数据库清理完成' AS result;